pull_request_title: "chore(i18n): new crowdin translations"
pull_request_labels:
  - crowdin
commit_message: "chore(i18n): new translations %original_file_name% (%language%)"
append_commit_message: false
files:
  - source: /shared/src/main/resources/locales/locale.json
    translation: /shared/src/main/resources/locales/locale_%osx_locale%.json
