name: SkinsRestorer
main: net.skinsrestorer.bukkit.SRBukkitBootstrap
load: STARTUP
version: ${version}
description: ${description}
website: ${url}
authors: [ "knat", "AlexProgrammerDE", "Th3Tr0LLeR", "McLive", "DoNotSpamPls" ]
softdepend: [ "ProtocolLib", "ViaVersion", "ViaBackwards", "ProtocolSupport", "MundoSK", "floodgate", "PlaceholderAPI", "MiniPlaceholders" ]
api-version: 1.13
folia-supported: true
